version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=change-this-secret-key-in-production
      - PORT=5000
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development services
  frontend-dev:
    image: node:18-alpine
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  backend-dev:
    image: node:18-alpine
    working_dir: /app
    command: npm run dev
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - JWT_SECRET=dev-secret-key
      - PORT=5000
    profiles:
      - dev 